let lsItem =
{
  "squads": [
    {
      "competitorId": 1215,
      "athletes": [
        {
          "age": 37,
          "jerseyNum": 23,
          "birthdate": "1987-04-22T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 5,
            "name": "Zagueiro Central",
            "order": 5
          },
          "height": 189,
          "id": 29,
          "name": "David Luiz",
          "shortName": "D. Luiz",
          "nameForURL": "david-luiz",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 22
        },
        {
          "age": 28,
          "jerseyNum": 10,
          "birthdate": "1996-08-30T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 12,
            "name": "Centroavante",
            "order": 12
          },
          "height": 178,
          "id": 3059,
          "name": "Gabriel Barbosa",
          "shortName": "Gabi",
          "nameForURL": "gabriel-barbosa",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 22
        },
        {
          "age": 28,
          "jerseyNum": 4,
          "birthdate": "1996-01-31T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 5,
            "name": "Zagueiro Central",
            "order": 5
          },
          "height": 189,
          "id": 3132,
          "name": "Léo Pereira",
          "shortName": "L. Pereira",
          "nameForURL": "leo-pereira",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 22
        },
        {
          "age": 39,
          "birthdate": "1985-08-09T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 0
          },
          "formationPosition": {
            "id": 16,
            "name": "Técnico",
            "order": 16
          },
          "height": 182,
          "id": 4272,
          "name": "Filipe Luís",
          "shortName": "F. Luís",
          "nameForURL": "filipe-luis",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 18
        },
        {
          "age": 28,
          "jerseyNum": 11,
          "birthdate": "1996-03-22T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 11,
            "name": "Ponta Esquerda",
            "order": 11
          },
          "height": 174,
          "id": 6907,
          "name": "Everton Cebolinha",
          "shortName": "Everton",
          "nameForURL": "everton",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 20
        },
        {
          "age": 33,
          "jerseyNum": 26,
          "birthdate": "1991-01-26T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 3,
            "name": "Lateral Esquerdo",
            "order": 3
          },
          "height": 181,
          "id": 7704,
          "name": "Alex Sandro",
          "nameForURL": "alex-sandro",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 31
        },
        {
          "age": 30,
          "jerseyNum": 14,
          "birthdate": "1994-06-01T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 9,
            "name": "Meia Atacante",
            "order": 9
          },
          "height": 174,
          "id": 9399,
          "name": "Giorgian De Arrascaeta",
          "nameForURL": "giorgian-de-arrascaeta",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 111,
          "nationalTeamId": 5073,
          "imageVersion": 8
        },
        {
          "age": 27,
          "jerseyNum": 8,
          "birthdate": "1997-05-20T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 8,
            "name": "Meio de Campo Central",
            "order": 8
          },
          "height": 184,
          "id": 9860,
          "name": "Gerson",
          "nameForURL": "gerson",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 7
        },
        {
          "age": 30,
          "jerseyNum": 5,
          "birthdate": "1994-01-14T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 4,
            "name": "Volante",
            "order": 4
          },
          "height": 186,
          "id": 13353,
          "name": "Erick Pulgar",
          "shortName": "Pulgar",
          "nameForURL": "erick-pulgar",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 28,
          "nationalTeamId": 5074,
          "imageVersion": 24
        },
        {
          "age": 29,
          "jerseyNum": 1,
          "birthdate": "1995-08-21T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 1,
            "name": "Goleiro"
          },
          "formationPosition": {
            "id": 1,
            "name": "Goleiro",
            "order": 1
          },
          "height": 193,
          "id": 14561,
          "name": "Agustin Rossi",
          "shortName": "Rossi",
          "nameForURL": "agustin-rossi",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 10,
          "nationalTeamId": 2378,
          "imageVersion": 14
        },
        {
          "age": 33,
          "jerseyNum": 27,
          "birthdate": "1990-12-30T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 11,
            "name": "Ponta Esquerda",
            "order": 11
          },
          "height": 184,
          "id": 14571,
          "name": "Bruno Henrique",
          "shortName": "B. Henrique",
          "nameForURL": "bruno-henrique",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 26
        },
        {
          "age": 27,
          "jerseyNum": 6,
          "birthdate": "1997-06-19T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 3,
            "name": "Lateral Esquerdo",
            "order": 3
          },
          "height": 180,
          "id": 39534,
          "name": "Ayrton Lucas",
          "shortName": "A. Lucas",
          "nameForURL": "ayrton-lucas",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 18
        },
        {
          "age": 31,
          "jerseyNum": 2,
          "birthdate": "1993-03-24T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 6,
            "name": "Lateral Direito",
            "order": 6
          },
          "height": 173,
          "id": 39827,
          "name": "Guillermo Varela",
          "shortName": "Varela",
          "nameForURL": "guillermo-varela",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 111,
          "nationalTeamId": 5073,
          "imageVersion": 34
        },
        {
          "age": 28,
          "jerseyNum": 15,
          "birthdate": "1996-02-12T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 5,
            "name": "Zagueiro Central",
            "order": 5
          },
          "height": 193,
          "id": 42215,
          "name": "Fabrício Bruno",
          "shortName": "F. Bruno",
          "nameForURL": "fabricio-bruno",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 26
        },
        {
          "age": 28,
          "jerseyNum": 7,
          "birthdate": "1996-06-02T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 14,
            "name": "Ponta Direita",
            "order": 14
          },
          "height": 175,
          "id": 42367,
          "name": "Luiz Araújo",
          "shortName": "L. Araújo",
          "nameForURL": "luiz-araujo",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 23
        },
        {
          "age": 27,
          "jerseyNum": 9,
          "birthdate": "1997-06-20T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 12,
            "name": "Centroavante",
            "order": 12
          },
          "height": 185,
          "id": 43663,
          "name": "Pedro",
          "nameForURL": "pedro",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 30
        },
        {
          "age": 27,
          "jerseyNum": 21,
          "birthdate": "1997-03-03T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 4,
            "name": "Volante",
            "order": 4
          },
          "height": 172,
          "id": 44287,
          "name": "Allan Souza",
          "shortName": "Allan",
          "nameForURL": "allan-souza",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 24
        },
        {
          "age": 27,
          "jerseyNum": 18,
          "birthdate": "1997-06-01T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 9,
            "name": "Meia Atacante",
            "order": 9
          },
          "height": 167,
          "id": 47168,
          "name": "Nicolas De La Cruz",
          "shortName": "De La Cruz",
          "nameForURL": "nicolas-de-la-cruz",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 111,
          "nationalTeamId": 5073,
          "imageVersion": 26
        },
        {
          "age": 26,
          "jerseyNum": 17,
          "birthdate": "1997-11-09T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 3,
            "name": "Lateral Esquerdo",
            "order": 3
          },
          "height": 180,
          "id": 47219,
          "name": "Matías Viña",
          "shortName": "Viña",
          "nameForURL": "matias-vina",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 111,
          "nationalTeamId": 5073,
          "imageVersion": 37
        },
        {
          "age": 28,
          "jerseyNum": 3,
          "birthdate": "1996-01-03T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 5,
            "name": "Zagueiro Central",
            "order": 5
          },
          "height": 185,
          "id": 48025,
          "name": "Léo Ortiz",
          "shortName": "L. Ortiz",
          "nameForURL": "leo-ortiz",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 13
        },
        {
          "age": 28,
          "jerseyNum": 30,
          "birthdate": "1996-03-12T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 11,
            "name": "Ponta Esquerda",
            "order": 11
          },
          "height": 166,
          "id": 48431,
          "name": "Michael",
          "nameForURL": "michael",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 20
        },
        {
          "age": 27,
          "jerseyNum": 12,
          "birthdate": "1997-02-12T00:00:00+00:00",
          "gender": 0,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 12,
            "name": "Centroavante",
            "order": 12
          },
          "height": 195,
          "id": 51145,
          "name": "Carlinhos",
          "nameForURL": "carlinhos",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 15
        },
        {
          "age": 24,
          "jerseyNum": 45,
          "birthdate": "2000-11-01T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 4,
            "name": "Atacante"
          },
          "formationPosition": {
            "id": 14,
            "name": "Ponta Direita",
            "order": 14
          },
          "height": 178,
          "id": 61732,
          "name": "Gonzalo Plata",
          "shortName": "Plata",
          "nameForURL": "gonzalo-plata",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 51,
          "nationalTeamId": 5075,
          "imageVersion": 18
        },
        {
          "age": 21,
          "jerseyNum": 37,
          "birthdate": "2002-11-30T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 8,
            "name": "Meio de Campo Central",
            "order": 8
          },
          "height": 183,
          "id": 80861,
          "name": "Carlos Alcaraz",
          "shortName": "Alcaraz",
          "nameForURL": "carlos-alcaraz",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 10,
          "nationalTeamId": 2378,
          "imageVersion": 22
        },
        {
          "age": 21,
          "jerseyNum": 43,
          "birthdate": "2003-09-06T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 6,
            "name": "Lateral Direito",
            "order": 6
          },
          "height": 173,
          "id": 105423,
          "name": "Wesley",
          "nameForURL": "wesley",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 11
        },
        {
          "age": 23,
          "jerseyNum": 25,
          "birthdate": "2001-05-24T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 1,
            "name": "Goleiro"
          },
          "formationPosition": {
            "id": 1,
            "name": "Goleiro",
            "order": 1
          },
          "height": 193,
          "id": 106444,
          "name": "Matheus Cunha",
          "shortName": "M. Cunha",
          "nameForURL": "matheus-cunha",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 13
        },
        {
          "age": 21,
          "jerseyNum": 33,
          "birthdate": "2003-05-24T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 2,
            "name": "Defesa"
          },
          "formationPosition": {
            "id": 5,
            "name": "Zagueiro Central",
            "order": 5
          },
          "height": 0,
          "id": 106445,
          "name": "Cleiton",
          "nameForURL": "cleiton-dos-santos",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 13
        },
        {
          "age": 19,
          "jerseyNum": 20,
          "birthdate": "2005-08-18T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 9,
            "name": "Meia Atacante",
            "order": 9
          },
          "height": 175,
          "id": 122160,
          "name": "Matheus Gonçalves",
          "shortName": "M. Gonçalves",
          "nameForURL": "matheus-goncalves",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 13
        },
        {
          "age": 21,
          "jerseyNum": 52,
          "birthdate": "2003-02-28T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 8,
            "name": "Meio de Campo Central",
            "order": 8
          },
          "height": 0,
          "id": 123219,
          "name": "Evertton Araujo",
          "shortName": "Evertton",
          "nameForURL": "evertton-araujo",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 4
        },
        {
          "age": 18,
          "jerseyNum": 19,
          "birthdate": "2006-07-04T00:00:00+00:00",
          "gender": 1,
          "position": {
            "id": 3,
            "name": "Meio-campo"
          },
          "formationPosition": {
            "id": 9,
            "name": "Meia Atacante",
            "order": 9
          },
          "height": 173,
          "id": 124700,
          "name": "Lorran",
          "nameForURL": "lorran",
          "sportId": 1,
          "clubId": 1215,
          "nationalityId": 21,
          "nationalTeamId": 2379,
          "imageVersion": 7
        }
      ],
      "positions": [
        {
          "id": 0,
          "name": "Gestão",
          "title": "Gestão",
          "isStaff": true
        },
        {
          "id": 1,
          "name": "Goleiro",
          "title": "Goleiros",
          "isStaff": false
        },
        {
          "id": 2,
          "name": "Defesa",
          "title": "Defensores",
          "isStaff": false
        },
        {
          "id": 3,
          "name": "Meio-campo",
          "title": "Meio Campistas",
          "isStaff": false
        },
        {
          "id": 4,
          "name": "Atacante",
          "title": "Atacantes",
          "isStaff": false
        }
      ]
    }
  ],
  "sports": [
    {
      "id": 1,
      "name": "Futebol",
      "nameForURL": "football",
      "drawSupport": true,
      "imageVersion": 1
    }
  ],
  "countries": [
    {
      "id": 21,
      "name": "Brasil",
      "nameForURL": "brazil",
      "sportTypes": [1, 2, 6, 8],
      "imageVersion": 1,
      "isInternational": false
    },
    {
      "id": 17,
      "name": "América do Sul",
      "nameForURL": "south-america",
      "sportTypes": [1, 2, 8, 9],
      "imageVersion": 1,
      "isInternational": true
    },
    {
      "id": 54,
      "name": "Internacional",
      "nameForURL": "international",
      "sportTypes": [1, 2, 4, 5, 7, 8, 9, 11, 13],
      "imageVersion": 1,
      "isInternational": true
    },
    {
      "id": 111,
      "name": "Uruguai",
      "nameForURL": "uruguay",
      "sportTypes": [1, 2],
      "imageVersion": 1,
      "isInternational": false
    },
    {
      "id": 28,
      "name": "Chile",
      "nameForURL": "chile",
      "sportTypes": [1, 2],
      "imageVersion": 1,
      "isInternational": false
    },
    {
      "id": 10,
      "name": "Argentina",
      "nameForURL": "argentina",
      "sportTypes": [1, 2, 5, 8, 9],
      "imageVersion": 1,
      "isInternational": false
    },
    {
      "id": 51,
      "name": "Equador",
      "nameForURL": "ecuador",
      "sportTypes": [1, 2],
      "imageVersion": 1,
      "isInternational": false
    }
  ],
  "competitions": [
    {
      "id": 102,
      "countryId": 17,
      "sportId": 1,
      "name": "Copa Libertadores",
      "hasStandings": true,
      "hasStandingsGroups": true,
      "hasBrackets": true,
      "hasStats": true,
      "nameForURL": "libertadores",
      "popularityRank": 49141436,
      "imageVersion": 6,
      "currentStageType": 3,
      "color": "#000000",
      "competitorsType": 1,
      "currentPhaseNum": -1,
      "currentSeasonNum": 67,
      "currentStageNum": 8,
      "isInternational": true,
      "hasHistory": true
    },
    {
      "id": 113,
      "countryId": 21,
      "sportId": 1,
      "name": "Brasileirão - Série A",
      "hasStandings": true,
      "hasLiveStandings": true,
      "hasStandingsGroups": false,
      "hasBrackets": false,
      "hasStats": true,
      "nameForURL": "brasileirao-serie-a",
      "popularityRank": 48072287,
      "imageVersion": 11,
      "currentStageType": 1,
      "color": "#01479A",
      "competitorsType": 1,
      "currentPhaseNum": -1,
      "currentSeasonNum": 74,
      "currentStageNum": 1,
      "isInternational": false,
      "hasHistory": true
    },
    {
      "id": 115,
      "countryId": 21,
      "sportId": 1,
      "name": "Copa do Brasil",
      "hasStandings": false,
      "hasBrackets": true,
      "hasStats": true,
      "nameForURL": "copa-do-brasil",
      "popularityRank": 35103491,
      "imageVersion": 4,
      "currentStageType": 3,
      "color": "#062381",
      "competitorsType": 1,
      "currentPhaseNum": -1,
      "currentSeasonNum": 37,
      "currentStageNum": 7,
      "isInternational": false,
      "hasHistory": true
    },
    {
      "id": 321,
      "countryId": 54,
      "sportId": 1,
      "name": "Amistoso",
      "hasStandings": false,
      "hasBrackets": false,
      "hasStats": false,
      "nameForURL": "club-friendlies",
      "popularityRank": 1917214,
      "imageVersion": 2,
      "currentStageType": 1,
      "color": "#326295",
      "competitorsType": 1,
      "currentPhaseNum": -1,
      "currentSeasonNum": -1,
      "currentStageNum": -1,
      "isInternational": true,
      "hasHistory": false
    },
    {
      "id": 418,
      "countryId": 21,
      "sportId": 1,
      "name": "Carioca",
      "hasStandings": true,
      "hasStandingsGroups": false,
      "hasBrackets": false,
      "hasStats": true,
      "nameForURL": "carioca",
      "popularityRank": 12495412,
      "imageVersion": 7,
      "currentStageType": 3,
      "color": "#000507",
      "competitorsType": 1,
      "currentPhaseNum": -1,
      "currentSeasonNum": 135,
      "currentStageNum": 3,
      "isInternational": false,
      "hasHistory": true
    },
    {
      "id": 6324,
      "countryId": 54,
      "sportId": 1,
      "name": "FC Series",
      "hasStandings": false,
      "hasBrackets": false,
      "hasStats": true,
      "nameForURL": "fc-series",
      "popularityRank": 338179,
      "imageVersion": 1,
      "currentStageType": 0,
      "color": "#43AD49",
      "competitorsType": 1,
      "currentSeasonNum": -1,
      "currentStageNum": 1,
      "isInternational": true,
      "hasHistory": false
    }
  ],
  "competitors": [
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    },
    {
      "id": 1215,
      "countryId": 21,
      "sportId": 1,
      "name": "Flamengo",
      "symbolicName": "FLA",
      "nameForURL": "flamengo",
      "type": 1,
      "popularityRank": 25659,
      "imageVersion": 5,
      "color": "#F20A0A",
      "mainCompetitionId": 113,
      "hasSquad": true,
      "hasTransfers": false,
      "competitorNum": 0,
      "hideOnSearch": false,
      "hideOnCatalog": false
    }
  ]
}